### ISSUE TITLE
Override incidence rate

### ISSUE THREAD

**Issue by LinqLover** [mathematica-mpr/covid_risk_score#110]
I live in Germany, and unfortunately incidence rates in my country are not yet connected in this tool. As a simple workaround, I would like to be able to enter a custom incidence rate instead.

Another use case for this feature would be to estimate your risk for past/future waves.

**Comment by xindyhu** [comment]
@LinqLover Thanks for raising those two great points!
The second feature you mentioned is in the works right now. Please stay tuned.
Unfortunately, we are not able to add more countries right now, but your idea is a good one. We also encourage international users to find a US zipcode with a similar incidence rate as their local community and use the calculator.
