### ISSUE TITLE
Enter behavior of contact persons

### ISSUE THREAD

**Issue by LinqLover** [mathematica-mpr/covid_risk_score#111]
For instance, I would like to take into consideration how many people my family members meet. Would this be possible or out of scope? :-)

**Comment by xindyhu** [comment]
@LinqLover Thanks for asking. These are considered the "indirect contacts". Please put those number in and the app will calculate for you.

**Comment by LinqLover** [comment]
This was probably a misconception. :-) I was talking about the question "In the previous week, I participated in the following activities", which I would like to be able to answer for my family members as well. I think it would make a big difference whether they only perform outdoor socially distanced activities or visit clubs every day. :-)
