### ISSUE TITLE
Feature request/suggestion

### ISSUE THREAD

**Issue by sarahgra** [mathematica-mpr/covid_risk_score#13]
Very cool app!
Maybe consider showing users expected chances of them contracting covid if they were to change behaviors for better or worse? Low chance of catching covid may lead to a false sense of security and relaxing of personal protection measures? (Haven't researched this to see if it's true)

**Comment by xindyhu** [comment]
@sarahgra Thank you for the suggestion. The app is interactive, so as the user changes their input the score and the expected changes of contracting COVID is showing in the app right now. You can see an example of this by visiting the blogpost on the Mathematica website.
https://www.mathematica.org/commentary/19-and-me-a-covid-19-risk-calculator
