### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Gushousekai195** [mathematica-mpr/covid_risk_score#132]
I am not able to calculate my risk of contracting covid with this tool.

It keeps giving me “internal server error.”

Please fix. There are no other tools like this, if not better.

**Comment by xindyhu** [comment]
Thanks @Gushousekai195 , we will look into this.  Most of our team is on PTO this week so we appreciate your patience. We will let you know when it is fixed.

**Comment by xindyhu** [comment]
Hi @Gushousekai195 , the error was caused by the underlying USAFacts data not updating over the holidays. Now they have resumed the data update the app is working fine again. Thank you for using this tool and for reporting this error.
