### ISSUE TITLE
Refine exposure risk calculation

### ISSUE THREAD

**Issue by xindyhu** [mathematica-mpr/covid_risk_score#18]
### Current methods
exposure = 1-(1-p)^n, where p is the prevalence of unreported active cases in the county
### Issues
1. recovered cases are not explicitly accounted for
2. Old cases from back in March are no longer relevant, so instead of cumulative cases, maybe use the number of new cases from a "relevant" period of time.
### Solutions
1. Literature search on what is a reasonable time frame for the new cases to be considered
2. NYT repo does not have recovered cases, can we bring in state-level recovered cases and calculate it for county-level?
3. One potential solution is p = new cases over X time - new recovered cases over X time - new deaths over X time.

**Comment by pendlrobinson** [comment]
1. People with mild symptom recover in about 2 weeks, people with more server symptoms might take 3-6 weeks. 
2. NYT does not have state level recovered. John Hopkins has state level recovered data for some states [link](https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6) and missing recovered data from states such as: MA, IL, CA, FL, OH, GA, WA. So I am not sure if it makes sense to use this data.
3. Possible solutions:
- Assume people with severe symptoms get all get tested and have symptoms for 4 weeks and mild symptoms do not get tested and get better in half the time as server cases. Then:
    -  `casecount = cases in last 4 weeks`
    - `total_covid_count = casecount + (casecount/2)*underreport_factor`
- Assume that some states behave like others. For example
   - If 74% of cases in CT are active maybe we can assume 74% of cases are active in MA

**Comment by xindyhu** [comment]
@pendlrobinson Good find! I didn't realize the JHU data was missing recovered case counts for some states but you are right! I like your solution 1. It's really tough to assume some states behave like others cuz they vary in demographics, healthcare resources, policy actions and pandemic dynamics.

**Comment by xindyhu** [comment]
@pendlrobinson implemented this change and merged PR#22
