### ISSUE TITLE
Tool works in USA only?

### ISSUE THREAD

**Issue by ba32107** [mathematica-mpr/covid_risk_score#41]
Hi,

This is a very interesting project, thank you. However I was not able to calculate my score, because my UK-based ZIP code is not 5 digits. I presume the tool only works in the USA - is that correct? If so, I believe a disclaimer should be added to the page, to make this explicit to international users.

**Comment by xindyhu** [comment]
@ba32107 thank you for your suggestion. We will add a disclaimer to make this clear.
